config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :recipes

  root 'home#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy" , :as => :signout

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	validates :name, presence:true, length:{minimum:2}
	validates :category, presence:true, length:{minimum:3}
	validates :instructions, presence:true
	validates :minutes_to_prepare, presence:true, numericality: {greater_than: 0}
	validates :minutes_to_cook, presence: true, numericality: {greater_than: 0}

	mount_uploader :image, ImageUploader


	def minutes_total
		minutes_to_prepare + minutes_to_cook
		
	end
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_with_omniauth(auth)
	create! do |user|
		user.provider = auth["provider"]
		user.uid = auth["uid"]
		user.name = auth["info"]["name"]
	end
end

def largeimage
	"http://graph.facebook.com/#{self.uid}/picture?type=large"
end

def normalimage
	"http://graph.facebook.com/#{self.uid}/picture?type=normal"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user

private

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]

end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :category, :ingredients, :instructions, :minutes_to_prepare, :minutes_to_cook, :image, :remote_image_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	auth = request.env["omniauth.auth"]
  	user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth) 
  	session[:user_id] = user.id 
  		redirect_to root_url, :notice => "Signed in!"
  	  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div id="user-widget">
	<% if current_user %>
	Welcome<strong><%= current_user.name %>
	</strong>!<br>
	<%= image_tag(current_user.normalimage) %><br>
	<%= link_to "Sign out", signout_path, id: "sign_out" %>

	<% else %>

	<%= link_to "Sign in with Facebook", "auth/facebook", id: "sign_in" %>
	<% end %>

	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

	<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '143092792721306',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= yield %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :minutes_to_prepare %><br>
    <%= f.number_field :minutes_to_prepare %>
  </div>
  <div class="field">
    <%= f.label :minutes_to_cook %><br>
    <%= f.number_field :minutes_to_cook %>
  </div>
  <div class="field">
    <%= f.label :image%><br>
    <%= f.file_field :image%></div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class ="field">
    <%= f.label :remote_image_url, "Or Image URL" %><br>
    <%= f.text_field :remote_image_url %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

<p id="notice"><%= notice %></p>

<h1 id="lst">Recipe Lists</h1>

<table>
  <style>
table {
    border: 1px solid black;
    font-size: 19px;
    font-family: times;
    color: #A80000;
}
th, td {
    padding: 15px;
    font-family: "Comic Sans MS", cursive, sans-serif;
}
</style>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Ingredients</th>
      <th>Instructions</th>
      <th>Minutes total</th>
      <th id="ige">Image</th>
      <th colspan="3"></th>

    </tr>
  </thead>
<!-- <img src="..." alt="..." class="img-rounded"> -->
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td id="nm"><%= recipe.name %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.instructions %></td>
        <td><%= recipe.minutes_total%></td>
        <td><img src="<%= recipe.image %>" alt="<%= recipe.image %>" class="img-rounded"></td>
        <td><button type="button" class="btn btn-warning btn-xs"><%= link_to 'Show', recipe %></button></td>
        <td><button id="edt" type="button" class="btn btn-warning btn-xs"><%= link_to 'Edit', edit_recipe_path(recipe) %></button></td>
        <td><button id="des" type="button" class="btn btn-warning btn-xs"><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-warning"><%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p id="inst1">
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p id="inst">
  <strong>Category:</strong>
  <%= @recipe.category %>
</p>

<p id="inst">
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p id="inst">
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p id="inst">
  <strong>Minutes to prepare:</strong>
  <%= @recipe.minutes_to_prepare %>
</p>

<p id="inst">
  <strong>Minutes to cook:</strong>
  <%= @recipe.minutes_to_cook %>
</p>

<p id="trk">
<strong></strong>
<%= image_tag @recipe.image_url if @recipe.image.present? %>
</p>

<a id="edt"><button  type="button" class="btn btn-warning"><%= link_to 'Edit', edit_recipe_path(@recipe) %></a>
<a id="edt"><button type="button" class="btn btn-warning"><%= link_to 'Back', recipes_path %></a>